# podman-compose.dev.yml
version: '3.8'

services:
  postgres:
    image: docker.io/postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak-dev:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # All cache-related settings
      KC_SPI_THEME_CACHE_THEMES: 'false'
      KC_SPI_THEME_CACHE_TEMPLATES: 'false'
      KC_SPI_THEME_STATIC_MAX_AGE: '-1'
      KC_SPI_THEME_DEFAULT: 'aquacloud'
      # Additional dev settings
      KC_LOG_LEVEL: 'INFO,org.keycloak.services.resources:DEBUG,org.keycloak.theme:DEBUG'
    volumes:
      - ./keycloak-themes/aquacloud:/opt/keycloak/themes/aquacloud:Z
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    # Important: Use start-dev with specific cache flags
    command: [
      "start-dev",
      "--spi-theme-static-max-age=-1",
      "--spi-theme-cache-themes=false",
      "--spi-theme-cache-templates=false"
    ]

volumes:
  postgres_data: